### ISSUE TITLE
Detail Accessory Category List

### ISSUE THREAD

**Issue by ArsenLuca** [XiaRho/SEMat#4]
Would u plz give the accessory categories belong to **person** category in **Accessory Fusion** step?

**Comment by XiaRho** [comment]
`{'person', 'vehicle', 'outdoor', 'animal', 'wine glass', 'furniture', 'appliance', 'tv', 'laptop', 'furniture-stuff', 'vase', 'cup'}`
Hi, we treat categories in the COCO dataset other than those listed above as possibly accessories. In addition, categories with ‘isthing’ = 0 are also not considered as accessories. For example: `{‘supercategory’: ‘building’, ‘isthing’: 0, ‘id’: 95, ‘name’: ‘bridge’}`
